# pVPN Control: "yes", "no", or "ask"
ENABLE_PVPN="yes"
PVPN_USER="gsfcu@proton.me"
PVPN_PASS="Test@1199"

# Active Directory Domain Configuration
DOMAIN_NAME="gsfcu.local"
REALM_NAME="GSFCU.LOCAL"
AD_DNS_IP="10.205.4.177"      # <-- REPLACE WITH YOUR ACTUAL AD DNS SERVER IP
DOMAIN_USER="admin"

# Username Short-Name Toggle ("yes" = log in as 'oslab', "no" = require 'oslab@gsfcu.local')
ALLOW_SHORT_USERNAMES="yes"
