# pVPN Control: "yes", "no", or "ask"
ENABLE_PVPN="yes"
PVPN_USER="gsfcu@proton.me"
PVPN_PASS="Test@1199"

# Active Directory Domain Configuration
DOMAIN_NAME="gsfcu.local"
REALM_NAME="GSFCU.LOCAL"
AD_DNS_IP="10.205.4.177"      # <-- REPLACE WITH YOUR ACTUAL AD DNS SERVER IP
DOMAIN_USER="admin"

# Username Short-Name Toggle ("yes" = log in as 'oslab', "no" = require 'oslab@gsfcu.local')
ALLOW_SHORT_USERNAMES="yes"

# Set policy refresh interval (e.g., 30m, 1h, 2h, 1d). Defaults to 1h if omitted.
REFRESH_INTERVAL="1hrs"

# System Timezone (Defaults to Indian Standard Time 'Asia/Kolkata')
SYSTEM_TIMEZONE="Asia/Kolkata"

# Intranet Primary Server Configuration
USE_INTRANET_FIRST="yes"
INTRANET_HOST_NAME="GSFCUPLLAB203"   # Hostname / mDNS domain of this server
INTRANET_FALLBACK_IP="10.205.18.253" # Backup IP if mDNS resolution fails
INTRANET_PORT="8080"

# Blocked Software Notification Message (shown when blocked software is detected and removed)
BLOCK_NOTIFICATION_TITLE="Unauthorized Application Blocked"
BLOCK_NOTIFICATION_MSG="Access Denied: This application is blacklisted under University IT Policy and has been terminated and removed."

# Unapproved Software Installation Academic Warning Message
ACADEMIC_WARNING_MSG="WARNING: This software is not pre-approved. If this package is found to be non-academic or violates institution policy, strict disciplinary action will be initiated."
