# Format -> HOSTNAME_PATTERN : PACKAGES_TO_INSTALL
GSFCUOSLAB : 
GSFCUPLLAB : 
GSFCUDSLAB : 
GSFCUDELAB : 
GSFCUAILAB : 
GSFCURALAB : 
GSFCURDLAB : 
GSFCUCCLAB : 
GSFCUBALAB : 
GSFCUCADLAB : 
GSFCUCSLAB : 
