# Format -> Lab Name:AD Group ID
Programming Lab:prolab
Operating Systems Lab:oslab
Data Science Lab:dslab
Data Engineering Lab:delab
AI/ML Lab:ailab
Robotic & Automation Lab:ralab
R & D Lab:rdlab
Computer Center Lab:cclab
Business Analytics Lab:balab
CAD Lab:cadlab
Cybersecurity Lab:cslab
