# Format -> Display Name : AD Group ID : Hostname Pattern
Programming Lab : prolab : GSFCUPLLAB
Operating Systems Lab:oslab : GSFCUOSLAB
Data Science Lab : dslab : GSFCUDSLAB
Data Engineering Lab : delab : GSFCUDELAB
AI/ML Lab : ailab : GSFCUAILAB
Robotic & Automation Lab : ralab : GSFCURALAB
R & D Lab : rdlab : GSFCURDLAB
Computer Center Lab : cclab : GSFCUCCLAB
Business Analytics Lab : balab : GSFCUBALAB
CAD Lab : cadlab : GSFCUCADLAB
Cybersecurity Lab : cslab : GSFCUCSLAB
