# ==============================================================================
# Native DNF / RPM Packages (Top Section)
# ==============================================================================


onlyoffice-desktopeditors
vlc
google-chrome-stable
chromium-browser.desktop
firefox
curl
git
kitty
haruna

# --- FLATPAK PACKAGES ---
# ==============================================================================
# Flatpak AppStream IDs (Bottom Section)
# ==============================================================================

com.vscodium.codium
com.google.Chrome