# ==============================================================================
# Native DNF / RPM Packages (Top Section)
# ==============================================================================


onlyoffice-desktopeditors
vlc
google-chrome-stable
firefox
curl
wget
git
kitty

# --- FLATPAK PACKAGES ---
# ==============================================================================
# Flatpak AppStream IDs (Bottom Section)
# ==============================================================================

com.vscodium.codium