# ==============================================================================
# Native DNF / RPM Packages to Block & Remove (Top Section)
# Wildcards supported (e.g., *steam*, *game*)
# ==============================================================================
*steam*
*game*
lutris
playonlinux
minetest
supertuxkart
kmahjongg
kmines
kpat
mines


# --- FLATPAK PACKAGES ---
# ==============================================================================
# Flatpak AppStream IDs to Uninstall & Block (Bottom Section)
# ==============================================================================
com.valvesoftware.Steam
net.lutris.Lutris
io.github.Faugus.faugus-launcher
com.heroicgameslauncher.hgl
org.DolphinEmu.dolphin-emu
org.PPSSPP.PPSSPP

# --- SYSTEM SETTINGS ---
# Set to true to disable user-level Flatpak installation for non-root users
BLOCK_ALL_FLATPAK_INSTALLS=false