DNF_EXCLUDE="*steam* *game* lutris playonlinux minetest supertuxkart"

# Flatpak App IDs to block explicitly
BLOCKED_FLATPAKS="com.valvesoftware.Steam io.github.Faugus.faugus-launcher com.heroicgameslauncher.hgl"

# Completely disable Flatpak installation for non-root users? (true/false)
BLOCK_ALL_FLATPAK_INSTALLS="false"
