# ==============================================================================
# Native DNF / RPM Packages (Top Section)
# ==============================================================================

onlyoffice-desktopeditors
curl
git
kitty

# --- FLATPAK PACKAGES ---
# ==============================================================================
# Flatpak AppStream IDs (Bottom Section)
# ==============================================================================

com.vscodium.codium