# ==============================================================================
# Native DNF / RPM Packages by Hostname Pattern (Top Section)
# Format -> HOSTNAME_PATTERN : package1 package2 package3 ...
# ==============================================================================
GSFCUOSLAB  : 
GSFCUPLLAB  : 
GSFCUDSLAB  : 
GSFCUDELAB  : 
GSFCUAILAB  : 
GSFCURALAB  : 
GSFCURDLAB  : 
GSFCUCCLAB  : 
GSFCUBALAB  : 
GSFCUCADLAB : 
GSFCUCSLAB  : 

# --- FLATPAK PACKAGES ---
# ==============================================================================
# Flatpak AppStream IDs by Hostname Pattern (Bottom Section)
# Format -> HOSTNAME_PATTERN : flatpak.id1 flatpak.id2 ...
# ==============================================================================
GSFCUOSLAB  : 
GSFCUPLLAB  : 
GSFCUDSLAB  : 
GSFCUDELAB  : 
GSFCUAILAB  : 
GSFCURALAB  : 
GSFCURDLAB  : 
GSFCUCCLAB  : 
GSFCUBALAB  : 
GSFCUCADLAB : 
GSFCUCSLAB  : 